sudo: required

language: python
python: "3.6"

services:
  - docker

stages:
  - lint
  - test
  - docker image

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

jobs:
  include:
    - stage: lint
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
    - stage: test
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install -v
      script:
        - pytest
    - stage: docker image
      script:
        - docker build -t genericmoniker/chorebot .
        - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push genericmoniker/chorebot
